name: Fix Models

on: [pull_request]

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==0.3.6"
      - name: Lint models
        run: "sqlfluff fix models --force --no-safety"
      
      - name: Commit diff
        run: |
          git add .
          git status
          git commit -m "fix(models/): format files"
          git status
          git push -u origin origin/${{ github.head_ref }}