name: Fix Models

on: [pull_request]

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==0.3.6"

      - name: Fix models
        run: "sqlfluff fix models --force --no-safety"
      
      - name: Set Git Config
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
          git config -l

      - name: Commit diff
        run: |
          git add models/*
          git status
          git commit -m "fix(models/): format files"
          git status
          git push --set-upstream origin ${{ github.head_ref }}